<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget_Collection */
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
        <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>
        <?php $i++ ?>
        <li class="item">
            <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                <?php //echo $this->helper('mtcepora')->getLabel($_product);  ?>
                <?php if ($carousel == 1): ?>
                    <img class="lazyOwl" src="<?php echo $helper->init($_product, 'small_image')->resize(210,268) ?>" width="210" height="268" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                <?php else: ?>
                    <img src="<?php echo $helper->init($_product, 'small_image')->resize(210,268) ?>" width="210" height="268" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                <?php endif ?>
            </a>
            <div class="product-date" data-date="<?php echo Mage::helper('mtwidget')->getDate($_product) ?>"></div>
            <div class="clear"></div>
            <div class="p-category-name"> Teste
                <?php
                $categoryIds = $_product->getCategoryIds();

                if(count($categoryIds) ){
                $firstCategoryId = $categoryIds[0];
                $_category = Mage::getModel('catalog/category')->load($firstCategoryId);

                echo $_category->getName();
                }
            ?>
            </div>


            <h3 class="product-name">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    <?php echo $this->escapeHtml($_product->getName()) ?>
                </a>
            </h3>

            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <div class="mt-actions clearfix">
                <div class="addtocart">
                    <?php if($_product->isSaleable()): ?>
                        <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) || $oType == true ) { ?>
                            <!--button type="button" title="<?php echo $this->__('Add To Cart') ?>"  data-placement="left" class="button btn-cart mt-tooltip <?php if($oType == true) echo 'option-file';?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                       <span>
                                                          <span><i class="fa-cart-plus"></i><?php echo $this->__('Add To Cart') ?></span>
                                                       </span>
                            </button-->
                        <?php } else { ?>
                            <?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) : ?>
                                <a style="display: none;" href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='options-cart' data-id='options-cart-<?php echo $_product->getId()?>'><?php echo $this->__('Option cart')?></a>
                            <?php endif; ?>
                            <!--button type="button" title="<?php echo $this->__('Add To Cart') ?>"  data-placement="left" class="button btn-cart show-options mt-tooltip" data-id="<?php echo $_product->getId(); ?>"
                                <?php if (!Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) { ?>
                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
                                <?php }?>><span><span><i class="fa mt-fa-shopping-cart"></i><?php echo $this->__('Add To Cart') ?></span></span></button-->
                        <?php }  ?>
                    <?php else: ?>
                        <p class="availability out-of-stock pull-left" title="<?php echo $this->__('Out of stock') ?>">
                            <span class="out"><?php echo $this->__('Out of stock') ?></span>
                        </p>
                    <?php endif; ?>
                    <div class="confix-produclist">
                        <div class="add-to-links">
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            </ul>
        <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>

&uarr;