<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>

<div class="add-to-cart addtocart">
  <?php if (!$_product->isGrouped()): ?>
  <!--label for="qty"><?php //echo $this->__('Quantity') ?></label>
            <div class="pull-left qty">
                <div class="custom-qty pull-left">
                    <button
                        onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 1 ) result.value--;return false;"
                        class="reduced items items-count" type="button">
                        <i class="fa fa-minus "></i>
                    </button>
                </div>
                <input type="hidden" name="qty" id="qty" maxlength="12"
                       value="1<?php //echo $this->getProductDefaultQty() * 1 ?>" title="<?php //echo $this->__('Qty') ?>"
                       class="input-text qty"/>

                <div class="custom-qty pull-left">
                    <button
                        onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;"
                        class="increase items items-count" type="button">
                        <i class="fa fa-plus"></i>
                    </button>
                </div>
            </div-->
  
  <input type="hidden" name="qty" id="qty" maxlength="12"
                       value="<?php echo $this->getProductDefaultQty() * 1  ?>" title="<?php //echo $this->__('Qty') ?>"
                       class="input-text qty"/>
  <?php endif; ?>
  <div class="clearfix"></div>
  <?php echo $this->getChildHtml('', true, true) ?> </div>
<div class="row text-center btn-comprar-produto"> <br />
  <button type="submit" title="<?php echo $buttonTitle ?>" class="btn-block btn-success btn-lg" onclick="productAddToCartForm.submit(this)"><i class="fa fa-cart-plus"></i> Comprar
  <?php //echo $buttonTitle ?>
  </button>
</div>
<?php endif; ?>
